### ISSUE TITLE
include package comparison table as appendix

### ISSUE THREAD

**Issue by dill** [dill/distance-package-paper#15]
Table [here](https://github.com/DistanceDevelopment/Distance/wiki/Feature-comparison), if updated, would probably make a good appendix

**Comment by erex** [comment]
That seems a reasonable addition

**Comment by dill** [comment]
Updated package comparison from the Distance wiki version in d3edfbe. Needs more work and to be intergrated into the paper as an appendix, rather than separate doc.

**Comment by lenthomas** [comment]
I think we can close this - table looks complete.
