### ISSUE TITLE
does there need to be more historical information?

### ISSUE THREAD

**Issue by dill** [dill/distance-package-paper#16]
e.g. about previous versions of DISTANCE -- what they were like, TRANSECT etc as in the JAE paper?

**Comment by dill** [comment]
see also #21

**Comment by erex** [comment]
I don't really think there needs to be more history; JAE paper covers that ground I think.  Unless there is merit mentioning keeping a working piece of software alive and relevant for ~20 years (e.g. software sustainability), I don't think the history is interesting in its own right

**Comment by dill** [comment]
Agreed. I've referenced the JAE paper for that purpose in c9fe5d9.
