### ISSUE TITLE
thank people who have worked on Distance/mrds

### ISSUE THREAD

**Issue by dill** [dill/distance-package-paper#17]
Who else has touched the code in `mrds`/`Distance`? So far I have:
- Jeff Laake
- Dave Miller
- Len Thomas
- Eric Rexstad
- Laura Marshall
- Jon Bishop
- Lorenzo Milazzo

**Comment by dill** [comment]
Colin Beale suggested the "flatfile" way of passing in data (e-mail from Len 04/12/2013).

**Comment by dill** [comment]
Added Jon and Lorenzo in 1c2debb

**Comment by erex** [comment]
Tiago hasn't touched code, but is always on hand with commentary.  Hard to justify DLB exclusion from `mrds`  Where should STB fit into this?

**Comment by dill** [comment]
Agreed. I've made this a more general thanks and added them in ea8092f.

**Comment by erex** [comment]
Now it feels a bit 'obvious' that everybody except Len and Laura are mentioned.

**Comment by dill** [comment]
I am expecting Len and Laura to also be authors, so I figure they don't need to be thanked additionally.

**Comment by lenthomas** [comment]
Thanks!

**Comment by dill** [comment]
Len: is there anyone else you can think of who should be thanked?
