### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by erex** [dill/distance-package-paper#18]
Dave

We found ourselves here before, how to incorporate comments into github rmd documents?  
- Are you happy to have me hack at the .rmd file and you 'diff' to see what suggestions are made?
- Do you want edits to happen continuously, or are there milestones you have in mind that should trigger a round of edits?
- I have a bug bear about "In order to" -> "To"
- Amakihi example (point transects) cries out for "real" PDF histograms rather than detection function histograms [we walked down this path back in July and again in September]
- I think your use of 'post-stratification' is inappropriate, because strata were defined at time of survey design, this is merely 'stratification', nothing 'post' about it

**Comment by dill** [comment]
Thanks for these Eric. In-order responses:
- In general I'm happy with hacking at the `.Rmd` directly.
- I don't mind this happening continuously, BUT I'd like to fill in the current gaps and look at the paper fully (removing silly mistakes) before I unleash it on anyone else.
- Feel free to go Strunk & White on it.
- Agreed, see #19
- Agreed, fine (though we should make it clear that post-stratification is possible).

**Comment by erex** [comment]
We could (albeit contrived) cook up post-stratification with the minke's.  Only possible variable is group size (only available at time of data collection), unless that wanders off into group size territory that we would rather avoid.  In which case, we could conjur (simulated data anyhow, I think you decided) a post-stratification factor, perhaps "female with calf"

**Comment by dill** [comment]
Sorry imprecise language on my part: I mean we should tell but perhaps don't need to show post-stratification is possible.

**Comment by erex** [comment]
As you wish; I don't know how many variations you would like to show off...

**Comment by dill** [comment]
I'm now in a position where I am happy enough for someone else to take a look. If you'd like to edit the paper directly that would be great (add your name to the author list too).

At this stage it would be good to get some general feedback about structure and content rather than really specific stuff, as there is a fair amount of finessing to do.

I wonder about one thing in particular: given the large amount of output from, e.g. `summary` and `dht`, do we want to explain what everything means? It seems like a big omission to not do this, but potentially it takes a lot of time and space. Thoughts?

**Comment by erex** [comment]
Timing of course is everything.  I can't really devote a solid hour or two to the manuscript before the weekend; end of semester (week 10 actually) onslaught in full flow.  Will however give a couple hours to 'meta issues' on the weekend (between bouts of marking).

**Comment by dill** [comment]
Sorry for the poor timing. In which case I'll attempt to spend some more 
time on this before the weekend.

**Comment by dill** [comment]
Thanks for your comments and adjustments in fbea2d966be26d96cae04d6e67223e8528713f86. I've taken into account those comments and made some alterations as of a599efd69f9270c680ba0930e6313b5a962bc00e.

**Comment by erex** [comment]
Hope to get another wack at the manuscript tomorrow morning; still drowning in MT4113 marking (that I told students I would get back to them today).

**Comment by dill** [comment]
No rush from my perspective. Thanks!
