### ISSUE TITLE
Should I backport plotting from Distance2 into Distance/mrds

### ISSUE THREAD

**Issue by dill** [dill/distance-package-paper#19]
Currently plots from `mrds`/`Distance` look like this:

![minke-hn-plot-1](https://cloud.githubusercontent.com/assets/1953/11148478/f4e400c0-89ea-11e5-849a-974ba4b6d2ab.png)

whereas in `Distance2` we have:

![dolphins-covar-beaufort-plot-1](https://cloud.githubusercontent.com/assets/1953/11148500/0fa31f7c-89eb-11e5-863f-7e4e3e7bbb54.png)

(three different data sets shown here, just examples).

I'd argue the second set are easier to interpret and read. Should I spend time backporting that code to `Distance` and/or `mrds` (the "or" here is really whether I need to spend what I think will actually be a fair amount of time getting this to work for MRDS models).

**Comment by dill** [comment]
Included in this is @erex's question (#18) on how to plot point transects.

**Comment by dill** [comment]
PDF plotting for point transects is done (some time ago).

I don't think that plotting lines rather than points is really worth it here.

**Comment by lenthomas** [comment]
How about having something that can turn the dots off (and possibly having them off by default).  I find them useful when plotting the detection function for one variable, in order that I can see how much variability arises from the other variables (shown by the scatter of the dots).

**Comment by dill** [comment]
This is possible via showpoints=FALSE argument to plot.ds.

I meant in my previous comment that it would be nice to have the 
"marginal" plots of the quantiles/levels of the detection function. I 
don't think this is essential for the paper though.
