### ISSUE TITLE
add distance downloads stat

### ISSUE THREAD

**Issue by dill** [dill/distance-package-paper#21]
We should tell people how popular we are.

**Comment by erex** [comment]
about time for a download stats summary anyhow.  Is that a pieces of business that somebody besides you knows how to perform?  Have you and Laura discussed?  Is there a piece of 'turn the crank' Rmarkdown for this?

**Comment by dill** [comment]
Laura and I have discussed this -- all code is available in [`download-stats`](https://github.com/DistanceDevelopment/download-stats).

Added a download statistic in 8e45917.
