### ISSUE TITLE
references need /pkg{} for packages

### ISSUE THREAD

**Issue by dill** [dill/distance-package-paper#23]
Broader issue is that the BibTeX is interpreted by `pandoc` and this probably isn't acceptable to JSS...

**Comment by LHMarshall** [comment]
I modified the bibtex entries to look like this:

@manual{mads-pkg,
title = {\pkg{mads}: Multi-Analysis Distance Sampling},
author = {Marshall, Laura},
year = {2015},
url = "http://CRAN.R-project.org/package=mads",
note = {\proglang{R} package version 0.1.3}
}

is that what you mean by references need /pkg{}?

The guidance for R packages on JSS is:

@Manual{rJava,
  title  = {\pkg{rJava}: Low-Level \proglang{R} to \proglang{Java} Interface},
  author = {Simon Urbanek},
  year   = {2009},
  note   = {\proglang{R}~package version~0.8-1},
  url    = {http://CRAN.R-project.org/package=rJava},
}
In any case, please make sure that the BibTeX is valid, that the title is in title style and that \proglang/\pkg/\code are used where appropriate.

**Comment by dill** [comment]
Perfect! Thanks Laura.
