### ISSUE TITLE
Include truncation in Figure 1?

### ISSUE THREAD

**Issue by dill** [dill/distance-package-paper#26]
Tiago suggests including the truncation in the plots and histograms in Figure 1, we can then introduce the idea of truncation there?

**Comment by erex** [comment]
Could do; would want to see truncation get as much attention as binning.  We'll not do sufficient justice to all things to do with analysis of distance sampling.

**Comment by dill** [comment]
On further reflection, not sure this is right place for this. We cover truncation on page 8.
