### ISSUE TITLE
Is the statement about the monotonicity assumption accurate enough

### ISSUE THREAD

**Issue by dill** [dill/distance-package-paper#27]
Tiago says: "this is confusing, because "this occurs" is strictly referring to being more likely to see distant than near objects. That cannot by definition be related to pi(x), since that is a statement about detectability!"

**Comment by erex** [comment]
Might be best to leave pi(x) out of that explanation, and say  we assume the process being modelled by the detection function is such that detectability falls away smoothly as a function of distance from the transect.

**Comment by lenthomas** [comment]
I had another look through the manuscript for all instances of the word Monotonic and I see no problem with any of them.  So, I'll close this issue.
