### ISSUE TITLE
Change "Cannot perform AIC adjustment term selection when covariates are used." error message?

### ISSUE THREAD

**Issue by dill** [dill/distance-package-paper#28]
Tiago says:

_Should the message be less criptic if it just said somethin like_

_"Warning: when covariates are included adjustment terms are not fitted"_

_I find this a weird message, since in the code there's no adjustments, so the user would not necessarily be expecting these to be fitted any way?_

_If it was me, the default would be no ajdustments. You want adjustments you include them manually!_

_Have you thought about not having defaults for parameters "key" and "adjustments", this would force people to know what they are doing and avoid the need for these warnings_

**Comment by erex** [comment]
Two issues:
covariates and adjustment terms
Fair enough; message could state: Model contains covariate term(s) no adjustment terms will be included.

k+a default
I don't feel too strongly about this; I understand Tiago's point.  At present, the behaviour of ds() mimics the behaviour of DisWin.  That may be a legacy, but I'm content for the two pieces of software to conform on this particular matter.

**Comment by dill** [comment]
[a5192b0](https://github.com/DistanceDevelopment/Distance/commit/a5192b0999cc73cfa0d3cb5130311b058ca26768) fixes the AIC message
