### ISSUE TITLE
References are still quite gross

### ISSUE THREAD

**Issue by dill** [dill/distance-package-paper#33]
Not sure what's going on but it's probably a `pandoc` issue.

**Comment by erex** [comment]
Author affiliations at beginning of article is also rugged.

**Comment by LHMarshall** [comment]
Dave what do you mean by references are still quite gross?

**Comment by dill** [comment]
Not sure what happened here -- they used to look really horrible in terms of first names vs. initialisations. They look fine now. Closing this.
