### ISSUE TITLE
Author affiliations poor formatting

### ISSUE THREAD

**Issue by LHMarshall** [dill/distance-package-paper#35]
The Author affiliations at the beginning of the paper end up on top of one another

(@erex I have created this new issue for this and will remove the related comment from the other issue)

**Comment by LHMarshall** [comment]
I have done a bit of investigating and I found that you can do a little tweak to the paper.tex file after it has been generated to improve this situation.

I read that for JSS style you use \And to seperate authors on the same line \and to seperate authors of the same institution on the same line (couldn't get this working!) and \AND to take a new line. So one option is as follows (but I have no idea what to do to the .Rmd file to get it to put this into the .tex file)

![screen shot 2016-01-05 at 15 45 24](https://cloud.githubusercontent.com/assets/1295691/12119564/58d4d1c4-b3c4-11e5-9eb3-d795e3992a32.png)

![screen shot 2016-01-05 at 15 45 12](https://cloud.githubusercontent.com/assets/1295691/12119577/6770268e-b3c4-11e5-9916-e8f10cd9d1be.png)

**Comment by dill** [comment]
Excellent! Thanks Laura! You're a wizard!
