### ISSUE TITLE
Inconsistency with data setup description in paper and in practise

### ISSUE THREAD

**Issue by LHMarshall** [dill/distance-package-paper#36]
I tried to do a basic analysis using only a vector of distances and it failed (should the vector of distances need to be put into a dataframe? I am using Package Distance version 0.9.5):
![screen shot 2016-02-01 at 12 32 24](https://cloud.githubusercontent.com/assets/1295691/12717487/281b3704-c8e0-11e5-92a4-7a56e238b71f.png)
![screen shot 2016-02-01 at 12 31 31](https://cloud.githubusercontent.com/assets/1295691/12717492/2bfd40e2-c8e0-11e5-8759-c669547a2bcf.png)

**Comment by dill** [comment]
Think this is hangover from when this was a paper about Distance2. This 
should be removed (unless someone wants me to add this feature).

**Comment by LHMarshall** [comment]
Awh bummer I was using it as a really cool selling point... I guess it would only take 5-10 min to add right?

If !is.dataframe ...
?

I think it would be really useful for people to be able to do something really simple during data collection for example. I was trying to use it for that reason.... while I was investigating how you code Q-Q plots (btw did you know Q-Q plots change when you change the truncation distance - both my truncation distances were larger than the largest recorded distance) 

Any way I really like my selling point "...Like the histogram function, the most basic detection function estimation only requires a numeric vector of distances. ..."

So yes I think it should be added :-) I think it is a great selling point

**Comment by dill** [comment]
Done in [319015e3448c06a942175d0a43bd895f2279e02e](https://github.com/DistanceDevelopment/Distance/commit/319015e3448c06a942175d0a43bd895f2279e02e)
