### ISSUE TITLE
Table 3 appears in the middle of some R output

### ISSUE THREAD

**Issue by LHMarshall** [dill/distance-package-paper#37]
Table 3 appears in the middle of some R output, it needs moved. Can we tell it to go to the bottom of that page?

**Comment by dill** [comment]
Arg, that's annoying. Let's revisit this once we get through the rest of the edits, as it's likely to move several times anyway. It's also possible the journal will deal with that kind of thing anyway.

**Comment by dill** [comment]
Closing this as we can look through the PDF once it's generated for this kind of problem.
