### ISSUE TITLE
Add further model selection discussion

### ISSUE THREAD

**Issue by LHMarshall** [dill/distance-package-paper#38]
We say that the hn model should be discarded based on fit but it is then included in the model comparison table... this should be explained

Add more guidance here on model selection and discussion on using AIC values. Although the AIC is smallest for amakihi.hr.obs.mas, some would argue that a difference of less than 2 does not really justify the inclusion of the additional covariate. Are there any other considerations to discuss? Probably good to point somewhere for further discussion on the topic?

**Comment by dill** [comment]
Added a wee bit of chat in 6719c72.
