### ISSUE TITLE
Should there be an appendix on plotting detection functions?

### ISSUE THREAD

**Issue by dill** [dill/distance-package-paper#4]
... and are there other topics that need treatment that this paper can deal with?

**Comment by dill** [comment]
More to the point, since we're now talking about `Distance`, is it worth trying to refrorm the plotting to be a bit less icky?

**Comment by erex** [comment]
Don't know what you have in mind to reduce ickiness; I think the plots are OK to my untrained eye

**Comment by dill** [comment]
Still not keen on the dots, but I think they are fine for this paper.

What are your thoughts on documenting how to plot detection functions/PDFs?

**Comment by lenthomas** [comment]
I always found this a bit tricky; on the other hand I'm not sure it's worth paper ink, is it?  Might make a good vignette or other related thing?  Don't feel strongly...

**Comment by dill** [comment]
Okay, I'll move this over to another project in that case.
