### ISSUE TITLE
Binned distances

### ISSUE THREAD

**Issue by dill** [dill/distance-package-paper#6]
At the moment there's no chat about binned distances.

This would also require some information about using chi^2 for goodness of fit.

**Comment by erex** [comment]
It is a small point (unless you collect data in bins) so I would be content to leave it out; particularly given the subjectivity of juggling cutpoints merely for the purpose of generating non-significant chisq P-values.

A sentence that states data collected in bins can be analysed by specification of cutpoints and recording of detection distances at midpoint between cutpoints might be sufficient.

**Comment by dill** [comment]
Agreed. I have included such a sentence in the data section as of a81b7a7.
