### ISSUE TITLE
detectability vs. average detectability vs. detection probability

### ISSUE THREAD

**Issue by dill** [dill/distance-package-paper#7]
Important to disambiguate between p_i and P_a.

**Comment by dill** [comment]
@erex raises the issue of what we should say about P_a -- why is this a useful metric, why is it included in the `summary` etc.

**Comment by lenthomas** [comment]
I love P_a (I call it p, typically) -- it's my favorite way to summarize the detection function into one number.  Not sure why really -- guess I don't find f(0) intuitive, and for some reason less keen on esw.  These comments not helpful for the paper, I guess...
P_a is the Horvitz-Thompson multiplier, once x is integrated out.  Intuitive and related to other methods such as mark recapture.  Hmmm.. not sure what else...

**Comment by dill** [comment]
I definitely prefer talking about P_a (or p) to mu/nu/f(0) etc. I think the link to mark-recapture is appealing here too. I'll have a hack at writing something about this tomorrow.
